/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ListingsNewRouteImport } from './routes/listings.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsNewRoute = ListingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ListingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/listings/new': typeof ListingsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/listings/new': typeof ListingsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/listings/new': typeof ListingsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/listings'
    | '/login'
    | '/logs'
    | '/settings'
    | '/listings/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/listings'
    | '/login'
    | '/logs'
    | '/settings'
    | '/listings/new'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/listings'
    | '/login'
    | '/logs'
    | '/settings'
    | '/listings/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ListingsRoute: typeof ListingsRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/new': {
      id: '/listings/new'
      path: '/new'
      fullPath: '/listings/new'
      preLoaderRoute: typeof ListingsNewRouteImport
      parentRoute: typeof ListingsRoute
    }
  }
}

interface ListingsRouteChildren {
  ListingsNewRoute: typeof ListingsNewRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsNewRoute: ListingsNewRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ListingsRoute: ListingsRouteWithChildren,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
