/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AggregationRouteImport } from './routes/aggregation'
import { Route as CooperativesRouteImport } from './routes/cooperatives'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GroupPurchasesRouteImport } from './routes/group-purchases'
import { Route as InputsRouteImport } from './routes/inputs'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as MarketPricesRouteImport } from './routes/market-prices'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TransportPoolRouteImport } from './routes/transport-pool'
import { Route as UsersRouteImport } from './routes/users'
import { Route as AggregationGroupIdRouteImport } from './routes/aggregation.$groupId'
import { Route as GroupPurchasesGroupPurchaseIdRouteImport } from './routes/group-purchases.$groupPurchaseId'
import { Route as InputsInputIdRouteImport } from './routes/inputs.$inputId'
import { Route as InputsNewRouteImport } from './routes/inputs.new'
import { Route as ListingsListingIdRouteImport } from './routes/listings.$listingId'
import { Route as ListingsNewRouteImport } from './routes/listings.new'
import { Route as RequestsRequestIdRouteImport } from './routes/requests.$requestId'
import { Route as RequestsNewRouteImport } from './routes/requests.new'
import { Route as TransactionsTransactionIdRouteImport } from './routes/transactions.$transactionId'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AggregationRoute = AggregationRouteImport.update({
  id: '/aggregation',
  path: '/aggregation',
  getParentRoute: () => rootRouteImport,
} as any)
const CooperativesRoute = CooperativesRouteImport.update({
  id: '/cooperatives',
  path: '/cooperatives',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupPurchasesRoute = GroupPurchasesRouteImport.update({
  id: '/group-purchases',
  path: '/group-purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const InputsRoute = InputsRouteImport.update({
  id: '/inputs',
  path: '/inputs',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketPricesRoute = MarketPricesRouteImport.update({
  id: '/market-prices',
  path: '/market-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportPoolRoute = TransportPoolRouteImport.update({
  id: '/transport-pool',
  path: '/transport-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AggregationGroupIdRoute = AggregationGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => AggregationRoute,
} as any)
const GroupPurchasesGroupPurchaseIdRoute =
  GroupPurchasesGroupPurchaseIdRouteImport.update({
    id: '/$groupPurchaseId',
    path: '/$groupPurchaseId',
    getParentRoute: () => GroupPurchasesRoute,
  } as any)
const InputsInputIdRoute = InputsInputIdRouteImport.update({
  id: '/$inputId',
  path: '/$inputId',
  getParentRoute: () => InputsRoute,
} as any)
const InputsNewRoute = InputsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InputsRoute,
} as any)
const ListingsListingIdRoute = ListingsListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => ListingsRoute,
} as any)
const ListingsNewRoute = ListingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ListingsRoute,
} as any)
const RequestsRequestIdRoute = RequestsRequestIdRouteImport.update({
  id: '/$requestId',
  path: '/$requestId',
  getParentRoute: () => RequestsRoute,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RequestsRoute,
} as any)
const TransactionsTransactionIdRoute =
  TransactionsTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () => TransactionsRoute,
  } as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aggregation': typeof AggregationRouteWithChildren
  '/cooperatives': typeof CooperativesRoute
  '/dashboard': typeof DashboardRoute
  '/group-purchases': typeof GroupPurchasesRouteWithChildren
  '/inputs': typeof InputsRouteWithChildren
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/market-prices': typeof MarketPricesRoute
  '/messages': typeof MessagesRoute
  '/my-listings': typeof MyListingsRoute
  '/register': typeof RegisterRoute
  '/requests': typeof RequestsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/transport-pool': typeof TransportPoolRoute
  '/users': typeof UsersRouteWithChildren
  '/aggregation/$groupId': typeof AggregationGroupIdRoute
  '/group-purchases/$groupPurchaseId': typeof GroupPurchasesGroupPurchaseIdRoute
  '/inputs/$inputId': typeof InputsInputIdRoute
  '/inputs/new': typeof InputsNewRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aggregation': typeof AggregationRouteWithChildren
  '/cooperatives': typeof CooperativesRoute
  '/dashboard': typeof DashboardRoute
  '/group-purchases': typeof GroupPurchasesRouteWithChildren
  '/inputs': typeof InputsRouteWithChildren
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/market-prices': typeof MarketPricesRoute
  '/messages': typeof MessagesRoute
  '/my-listings': typeof MyListingsRoute
  '/register': typeof RegisterRoute
  '/requests': typeof RequestsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/transport-pool': typeof TransportPoolRoute
  '/users': typeof UsersRouteWithChildren
  '/aggregation/$groupId': typeof AggregationGroupIdRoute
  '/group-purchases/$groupPurchaseId': typeof GroupPurchasesGroupPurchaseIdRoute
  '/inputs/$inputId': typeof InputsInputIdRoute
  '/inputs/new': typeof InputsNewRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aggregation': typeof AggregationRouteWithChildren
  '/cooperatives': typeof CooperativesRoute
  '/dashboard': typeof DashboardRoute
  '/group-purchases': typeof GroupPurchasesRouteWithChildren
  '/inputs': typeof InputsRouteWithChildren
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/market-prices': typeof MarketPricesRoute
  '/messages': typeof MessagesRoute
  '/my-listings': typeof MyListingsRoute
  '/register': typeof RegisterRoute
  '/requests': typeof RequestsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/transport-pool': typeof TransportPoolRoute
  '/users': typeof UsersRouteWithChildren
  '/aggregation/$groupId': typeof AggregationGroupIdRoute
  '/group-purchases/$groupPurchaseId': typeof GroupPurchasesGroupPurchaseIdRoute
  '/inputs/$inputId': typeof InputsInputIdRoute
  '/inputs/new': typeof InputsNewRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aggregation'
    | '/cooperatives'
    | '/dashboard'
    | '/group-purchases'
    | '/inputs'
    | '/listings'
    | '/login'
    | '/logs'
    | '/market-prices'
    | '/messages'
    | '/my-listings'
    | '/register'
    | '/requests'
    | '/settings'
    | '/transactions'
    | '/transport-pool'
    | '/users'
    | '/aggregation/$groupId'
    | '/group-purchases/$groupPurchaseId'
    | '/inputs/$inputId'
    | '/inputs/new'
    | '/listings/$listingId'
    | '/listings/new'
    | '/requests/$requestId'
    | '/requests/new'
    | '/transactions/$transactionId'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aggregation'
    | '/cooperatives'
    | '/dashboard'
    | '/group-purchases'
    | '/inputs'
    | '/listings'
    | '/login'
    | '/logs'
    | '/market-prices'
    | '/messages'
    | '/my-listings'
    | '/register'
    | '/requests'
    | '/settings'
    | '/transactions'
    | '/transport-pool'
    | '/users'
    | '/aggregation/$groupId'
    | '/group-purchases/$groupPurchaseId'
    | '/inputs/$inputId'
    | '/inputs/new'
    | '/listings/$listingId'
    | '/listings/new'
    | '/requests/$requestId'
    | '/requests/new'
    | '/transactions/$transactionId'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/aggregation'
    | '/cooperatives'
    | '/dashboard'
    | '/group-purchases'
    | '/inputs'
    | '/listings'
    | '/login'
    | '/logs'
    | '/market-prices'
    | '/messages'
    | '/my-listings'
    | '/register'
    | '/requests'
    | '/settings'
    | '/transactions'
    | '/transport-pool'
    | '/users'
    | '/aggregation/$groupId'
    | '/group-purchases/$groupPurchaseId'
    | '/inputs/$inputId'
    | '/inputs/new'
    | '/listings/$listingId'
    | '/listings/new'
    | '/requests/$requestId'
    | '/requests/new'
    | '/transactions/$transactionId'
    | '/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AggregationRoute: typeof AggregationRouteWithChildren
  CooperativesRoute: typeof CooperativesRoute
  DashboardRoute: typeof DashboardRoute
  GroupPurchasesRoute: typeof GroupPurchasesRouteWithChildren
  InputsRoute: typeof InputsRouteWithChildren
  ListingsRoute: typeof ListingsRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  MarketPricesRoute: typeof MarketPricesRoute
  MessagesRoute: typeof MessagesRoute
  MyListingsRoute: typeof MyListingsRoute
  RegisterRoute: typeof RegisterRoute
  RequestsRoute: typeof RequestsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRouteWithChildren
  TransportPoolRoute: typeof TransportPoolRoute
  UsersRoute: typeof UsersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aggregation': {
      id: '/aggregation'
      path: '/aggregation'
      fullPath: '/aggregation'
      preLoaderRoute: typeof AggregationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cooperatives': {
      id: '/cooperatives'
      path: '/cooperatives'
      fullPath: '/cooperatives'
      preLoaderRoute: typeof CooperativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-purchases': {
      id: '/group-purchases'
      path: '/group-purchases'
      fullPath: '/group-purchases'
      preLoaderRoute: typeof GroupPurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inputs': {
      id: '/inputs'
      path: '/inputs'
      fullPath: '/inputs'
      preLoaderRoute: typeof InputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-prices': {
      id: '/market-prices'
      path: '/market-prices'
      fullPath: '/market-prices'
      preLoaderRoute: typeof MarketPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings': {
      id: '/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport-pool': {
      id: '/transport-pool'
      path: '/transport-pool'
      fullPath: '/transport-pool'
      preLoaderRoute: typeof TransportPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aggregation/$groupId': {
      id: '/aggregation/$groupId'
      path: '/$groupId'
      fullPath: '/aggregation/$groupId'
      preLoaderRoute: typeof AggregationGroupIdRouteImport
      parentRoute: typeof AggregationRoute
    }
    '/group-purchases/$groupPurchaseId': {
      id: '/group-purchases/$groupPurchaseId'
      path: '/$groupPurchaseId'
      fullPath: '/group-purchases/$groupPurchaseId'
      preLoaderRoute: typeof GroupPurchasesGroupPurchaseIdRouteImport
      parentRoute: typeof GroupPurchasesRoute
    }
    '/inputs/$inputId': {
      id: '/inputs/$inputId'
      path: '/$inputId'
      fullPath: '/inputs/$inputId'
      preLoaderRoute: typeof InputsInputIdRouteImport
      parentRoute: typeof InputsRoute
    }
    '/inputs/new': {
      id: '/inputs/new'
      path: '/new'
      fullPath: '/inputs/new'
      preLoaderRoute: typeof InputsNewRouteImport
      parentRoute: typeof InputsRoute
    }
    '/listings/$listingId': {
      id: '/listings/$listingId'
      path: '/$listingId'
      fullPath: '/listings/$listingId'
      preLoaderRoute: typeof ListingsListingIdRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/listings/new': {
      id: '/listings/new'
      path: '/new'
      fullPath: '/listings/new'
      preLoaderRoute: typeof ListingsNewRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/requests/$requestId': {
      id: '/requests/$requestId'
      path: '/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof RequestsRequestIdRouteImport
      parentRoute: typeof RequestsRoute
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof RequestsRoute
    }
    '/transactions/$transactionId': {
      id: '/transactions/$transactionId'
      path: '/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof TransactionsTransactionIdRouteImport
      parentRoute: typeof TransactionsRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRoute
    }
  }
}

interface AggregationRouteChildren {
  AggregationGroupIdRoute: typeof AggregationGroupIdRoute
}

const AggregationRouteChildren: AggregationRouteChildren = {
  AggregationGroupIdRoute: AggregationGroupIdRoute,
}

const AggregationRouteWithChildren = AggregationRoute._addFileChildren(
  AggregationRouteChildren,
)

interface GroupPurchasesRouteChildren {
  GroupPurchasesGroupPurchaseIdRoute: typeof GroupPurchasesGroupPurchaseIdRoute
}

const GroupPurchasesRouteChildren: GroupPurchasesRouteChildren = {
  GroupPurchasesGroupPurchaseIdRoute: GroupPurchasesGroupPurchaseIdRoute,
}

const GroupPurchasesRouteWithChildren = GroupPurchasesRoute._addFileChildren(
  GroupPurchasesRouteChildren,
)

interface InputsRouteChildren {
  InputsInputIdRoute: typeof InputsInputIdRoute
  InputsNewRoute: typeof InputsNewRoute
}

const InputsRouteChildren: InputsRouteChildren = {
  InputsInputIdRoute: InputsInputIdRoute,
  InputsNewRoute: InputsNewRoute,
}

const InputsRouteWithChildren =
  InputsRoute._addFileChildren(InputsRouteChildren)

interface ListingsRouteChildren {
  ListingsListingIdRoute: typeof ListingsListingIdRoute
  ListingsNewRoute: typeof ListingsNewRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsListingIdRoute: ListingsListingIdRoute,
  ListingsNewRoute: ListingsNewRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

interface RequestsRouteChildren {
  RequestsRequestIdRoute: typeof RequestsRequestIdRoute
  RequestsNewRoute: typeof RequestsNewRoute
}

const RequestsRouteChildren: RequestsRouteChildren = {
  RequestsRequestIdRoute: RequestsRequestIdRoute,
  RequestsNewRoute: RequestsNewRoute,
}

const RequestsRouteWithChildren = RequestsRoute._addFileChildren(
  RequestsRouteChildren,
)

interface TransactionsRouteChildren {
  TransactionsTransactionIdRoute: typeof TransactionsTransactionIdRoute
}

const TransactionsRouteChildren: TransactionsRouteChildren = {
  TransactionsTransactionIdRoute: TransactionsTransactionIdRoute,
}

const TransactionsRouteWithChildren = TransactionsRoute._addFileChildren(
  TransactionsRouteChildren,
)

interface UsersRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AggregationRoute: AggregationRouteWithChildren,
  CooperativesRoute: CooperativesRoute,
  DashboardRoute: DashboardRoute,
  GroupPurchasesRoute: GroupPurchasesRouteWithChildren,
  InputsRoute: InputsRouteWithChildren,
  ListingsRoute: ListingsRouteWithChildren,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  MarketPricesRoute: MarketPricesRoute,
  MessagesRoute: MessagesRoute,
  MyListingsRoute: MyListingsRoute,
  RegisterRoute: RegisterRoute,
  RequestsRoute: RequestsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRouteWithChildren,
  TransportPoolRoute: TransportPoolRoute,
  UsersRoute: UsersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
